controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"
    brain_controller:
      type: "brain_controller/BrainController"

joint_state_broadcaster:
  ros__parameters:
    {}

brain_controller:
  ros__parameters:
    wheel_radius: 0.04
    wheel_separation_h: 0.18
    wheel_separation_w: 0.173
    max_speed: 1.33 #rs
    cmd_vel_topic: "/cmd_vel_safe"